'use strict';

var gulp = require('gulp');
// var exec = require('gulp-exec');
var nodemon = require('gulp-nodemon')

gulp.paths = {
  scripts: ['routes/*.js', 'utils/*.js'
  ],
};

gulp.task('dev-server', function() {
  // exec('node bin/www');
  // exec('node bin/www', function (err, stdout, stderr) {
  //   console.log(stdout);
  //   console.log(stderr);
  //   cb(err);
  // });
  nodemon({
      script: 'bin/www',
      ext: 'js'
    });
});

/**
 * separating gulp tasks concerns inside the gulp dir
 * NOTE: tasks in this directory have been adapted from
 * tasks generated by github.com/kosz/generator-modular
 */
require('require-dir')('./gulp');
